import { execFile } from 'node:child_process'
import path from 'node:path'
import { promisify } from 'node:util'
import { ffmpeg, ffmpegPath, ffprobeAsync, runFfmpeg } from './ffmpeg.js'
import { ensureDir } from './paths.js'

/** Narration sits at broadcast level: -16 LUFS with 1.5 dB of true-peak headroom. */
const LOUDNORM_VOICE = 'loudnorm=I=-16:TP=-1.5:LRA=11'

/** The bed sits a good 8 LU below the voice before any ducking is applied. */
const LOUDNORM_MUSIC = 'loudnorm=I=-24:TP=-2:LRA=11'

export interface VoiceClip {
  filePath: string
  /** Where the line starts on the film's timeline. */
  offsetSec: number
}

const run = promisify(execFile)

/**
 * Seconds of audio in a file, or 0 if it has none. The container's duration is
 * read first: some AAC streams report a nonsense per-stream duration.
 */
export async function audioDuration(filePath: string): Promise<number> {
  const data = await ffprobeAsync(filePath)
  const stream = data.streams.find((s) => s.codec_type === 'audio')
  const seconds = Number(data.format?.duration ?? stream?.duration ?? 0)
  return Number.isFinite(seconds) && seconds > 0 ? seconds : 0
}

/**
 * Lays each narration line at its own offset on one silent bed the length of the
 * film. Lines are placed, never concatenated: the EDL decides when each is
 * spoken, and concatenation would let a long line push everything after it out
 * of sync with the picture.
 */
export async function buildVoiceTrack(
  clips: VoiceClip[],
  totalSec: number,
  outputPath: string,
): Promise<void> {
  await ensureDir(path.dirname(outputPath))

  // Built by calling ffmpeg directly rather than through fluent-ffmpeg: the
  // graph starts from a silent bed generated by lavfi, and fluent validates any
  // input format against `ffmpeg -formats`, which does not list lavfi.
  const args = [
    '-y', '-hide_banner', '-loglevel', 'error',
    // Input 0: silence the length of the film. Every line is mixed onto it, so
    // the track starts at zero and runs the full duration whatever the lines do.
    // Delaying a line without this base leaves ffmpeg writing a container start
    // offset instead of real leading silence, and the narration plays early.
    '-f', 'lavfi', '-t', totalSec.toFixed(3),
    '-i', 'anullsrc=channel_layout=stereo:sample_rate=48000',
  ]

  for (const clip of clips) args.push('-i', clip.filePath)

  const delays = clips.map((clip, index) => {
    const ms = Math.max(0, Math.round(clip.offsetSec * 1000))
    // Each line is normalised to broadcast level before it is placed. TTS
    // output level varies by voice and by line, and the ducking downstream keys
    // off this track — an unpredictable key means unpredictable ducking.
    return `[${index + 1}:a]aresample=48000,${LOUDNORM_VOICE},aresample=48000,adelay=${ms}|${ms}[v${index}]`
  })

  const mixInputs = ['[0:a]', ...clips.map((_, index) => `[v${index}]`)].join('')
  // normalize=0 keeps each line at the level it was generated; duration=first
  // ends the mix with the silent bed, so the track is exactly the film's length.
  const graph = [
    ...delays,
    `${mixInputs}amix=inputs=${clips.length + 1}:normalize=0:duration=first[out]`,
  ].join(';')

  args.push(
    '-filter_complex', graph,
    '-map', '[out]',
    '-ac', '2', '-ar', '48000',
    '-c:a', 'aac', '-b:a', '192k',
    outputPath,
  )

  await run(ffmpegPath, args)
}

export interface DuckOptions {
  voicePath: string
  musicPath: string
  totalSec: number
  outputPath: string
  /** Music level before ducking, 0..1. */
  musicGain?: number
}

/**
 * Mixes music under the narration with sidechain compression: the voice itself
 * drives the gain reduction, so the bed drops when someone speaks and comes back
 * up in the gaps. A fixed low level would either bury the music or fight the
 * voice, depending on the track.
 */
export async function duckMusicUnderVoice(options: DuckOptions): Promise<void> {
  const { voicePath, musicPath, totalSec, outputPath } = options
  const gain = options.musicGain ?? 0.7
  await ensureDir(path.dirname(outputPath))

  await runFfmpeg(
    ffmpeg()
      .input(voicePath)
      .input(musicPath)
      // Short tracks are looped rather than cut off mid-film.
      .inputOptions('-stream_loop', '-1')
      .complexFilter([
        `[0:a]aresample=48000,apad,atrim=0:${totalSec.toFixed(3)}[voice]`,
        // Normalising the bed first means the same settings duck any track by
        // the same amount, whether it arrived hot or quiet.
        `[1:a]aresample=48000,atrim=0:${totalSec.toFixed(3)},${LOUDNORM_MUSIC},volume=${gain}[bed]`,
        '[voice]asplit=2[voicemix][key]',
        // Speech pulls the bed down by roughly 10 dB, with a slow release so it
        // does not pump between words.
        '[bed][key]sidechaincompress=threshold=0.05:ratio=8:attack=15:release=450:detection=rms:makeup=1[ducked]',
        '[voicemix][ducked]amix=inputs=2:normalize=0,alimiter=limit=0.97[out]',
      ])
      .outputOptions('-map', '[out]', '-ac', '2', '-ar', '48000')
      .audioCodec('aac')
      .audioBitrate('192k')
      .output(outputPath),
  )
}

/** Music with no narration: just trimmed, looped and levelled. */
export async function musicOnlyTrack(
  musicPath: string,
  totalSec: number,
  outputPath: string,
  gain = 1,
): Promise<void> {
  await ensureDir(path.dirname(outputPath))
  await runFfmpeg(
    ffmpeg()
      .input(musicPath)
      .inputOptions('-stream_loop', '-1')
      .audioFilters([
        `atrim=0:${totalSec.toFixed(3)}`,
        'aresample=48000',
        LOUDNORM_MUSIC,
        `volume=${gain}`,
      ])
      .audioCodec('aac')
      .audioBitrate('192k')
      .output(outputPath),
  )
}
